# Previsione Abbandono Universitario

## 1. Preparazione del dataset
Importiamo le librerie necessarie per la creazione del modello.

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import make_classification
from sklearn.model_selection import (
    train_test_split, cross_val_score, KFold, GridSearchCV
)
from sklearn.metrics import accuracy_score, classification_report, f1_score
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from xgboost import XGBClassifier

RANDOM_STATE = 42

## 2. Esplorazione del Dataset

Incorporiamo il file train_dropout.csv per vedere le colonne ed esplorare i dati.

In [4]:
df = pd.read_csv('./CSV/train_dropout.csv')

In [5]:
df.head()

,Marital status,Application mode,Application order,Course,Daytime/evening attendance\t,Previous qualification,Previous qualification (grade),Nacionality,Mother's qualification,Father's qualification,...,Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP,Target
0,1,44,1,9003,1,39,150.0,1,19,37,...,0,6,7,6,13.833333,0,13.9,-0.3,0.79,Graduate
1,2,39,1,9991,0,1,135.0,1,34,34,...,0,5,5,0,0.000000,0,7.6,2.6,0.32,Dropout
2,1,1,1,9238,1,1,121.0,1,1,1,...,0,6,7,6,12.142857,0,11.1,0.6,2.02,Graduate
3,1,1,4,9500,1,1,135.0,1,37,37,...,0,8,8,7,13.381429,0,10.8,1.4,1.74,Graduate
4,2,39,1,8014,0,12,110.0,1,34,34,...,2,6,9,6,12.500000,0,7.6,2.6,0.32,Graduate

In [6]:
df.describe()

,Marital status,Application mode,Application order,Course,Daytime/evening attendance\t,Previous qualification,Previous qualification (grade),Nacionality,Mother's qualification,Father's qualification,...,Curricular units 1st sem (without evaluations),Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP
count,2904.000000,2904.000000,2904.000000,2904.000000,2904.000000,2904.000000,2904.000000,2904.000000,2904.000000,2904.000000,...,2904.000000,2904.000000,2904.000000,2904.000000,2904.000000,2904.000000,2904.000000,2904.000000,2904.000000,2904.000000
mean,1.185606,18.415289,1.746901,8848.062328,0.888430,4.621212,132.986191,1.755165,20.032369,22.588843,...,0.126033,0.585744,6.288912,7.753099,4.505854,10.014150,0.133264,11.660537,1.227789,0.001009
std,0.613028,17.335091,1.329204,2077.051948,0.314891,10.162905,13.176359,6.206597,15.585075,15.263052,...,0.666059,2.011391,2.252767,3.975813,3.158457,5.499942,0.717246,2.668650,1.380022,2.252360
min,1.000000,1.000000,0.000000,33.000000,0.000000,1.000000,95.000000,1.000000,1.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7.600000,-0.800000,-4.060000
25%,1.000000,1.000000,1.000000,9085.000000,1.000000,1.000000,125.000000,1.000000,2.000000,3.000000,...,0.000000,0.000000,5.000000,6.000000,2.000000,10.500000,0.000000,9.400000,0.300000,-1.700000
50%,1.000000,17.000000,1.000000,9238.000000,1.000000,1.000000,133.100000,1.000000,19.000000,19.000000,...,0.000000,0.000000,6.000000,8.000000,5.000000,12.333333,0.000000,11.100000,1.400000,0.320000
75%,1.000000,39.000000,2.000000,9556.000000,1.000000,1.000000,140.000000,1.000000,37.000000,37.000000,...,0.000000,0.000000,7.000000,10.000000,6.000000,13.500000,0.000000,13.900000,2.600000,1.790000
max,6.000000,57.000000,6.000000,9991.000000,1.000000,43.000000,190.000000,105.000000,44.000000,44.000000,...,12.000000,19.000000,23.000000,33.000000,20.000000,18.571429,12.000000,16.200000,3.700000,3.510000